name: text-categorizer
channels:
- pytorch
dependencies:
- pip==19.1.1
- python==3.7.6
- pytorch==1.4.0
- torchvision==0.5.0
- cudatoolkit==10.1.243
- pip:
  - pandas==0.24.1
  - xlrd==1.2.0
  - nltk==3.4
  - numpy==1.16.1
  - scikit-learn==0.20.3
  - tqdm==4.31.1
  - stanza==1.0.0
  - openpyxl==3.0.3
